### ISSUE TITLE
Print menu improvement

### ISSUE THREAD

**Issue by PsykeDady** [Leonia-Tech/TextEd#11]
please, add tab character in order to distinguish commands from options ( + char is not really clear in my opinion) 

I expect a similar output from help menu: 

```
--HELP--

Every option of a command must be write attach to command (few exceptions)

p              print
	l              current line
	n             with line numbers
	ln            n option and l option togheter
	 -p            print permissions (need space before option) 

i              insert mode
	w		save after quitting insert mode
              
esc            exit insert mode

w              save
x              save and exit
b              generate backup file
q              quit

s              substitute word (ed syntax)
m              add word before ... (ed syntax)
a              append at the end of the edit line
l              set edit line

n              add a new line before the edit line
d              remove the edit line
```

P.S.: how to change line to print??? is not clear :/ and not specified, is bad idea to add to `pn` command number of line to print???

**Comment by LoZack19** [comment]
Now you can use the `pn <num>` command to print the `num`-th line without changing the current line. I won't close this issue untill I'm sure it hasn't brought any new bugs.

**Comment by PsykeDady** [comment]
pn work on my pc! 
help is not "tabbet" but i found more clear than other, so imho it' good 

Thanks :D 
![image](https://user-images.githubusercontent.com/27916449/113414501-6b1b8600-93bd-11eb-8e76-6897825fb64d.png)

**Comment by LoZack19** [comment]
Now `pn` was changed to `pl` for better coherence. `l` stands for line.
All the testings suggest there are no bugs in this function. Thanks for the suggestion.
