### ISSUE TITLE
Read only file issue with release 1.0

### ISSUE THREAD

**Issue by FrancescoLFM** [Leonia-Tech/TextEd#2]
When I open read only files, the program says "Written.. bytes", then starts to answer "invalid command" every time I write a **correct** command
![Screenshot_20210322_115156](https://user-images.githubusercontent.com/60569057/111979155-0599e080-8b05-11eb-9f7f-4fba278d1a64.png)

**Comment by LoZack19** [comment]
Check out this commit: https://github.com/Leonia-Tech/TextEd/commit/de4923c40625299994f1b5ef750489913e92a824
If you still notice this bugs report them here.

**Comment by LoZack19** [comment]
Created a new one which describes the same problem.
