### ISSUE TITLE
No errors are shown while trying to edit a read only file

### ISSUE THREAD

**Issue by FrancescoLFM** [Leonia-Tech/TextEd#5]
![Screenshot_20210323_152107](https://user-images.githubusercontent.com/60569057/112161934-e0cc6880-8beb-11eb-9b44-fb338a70b692.png)

**Comment by LoZack19** [comment]
Did you try with the latest release? I think this issue was fixed after commit https://github.com/Leonia-Tech/TextEd/commit/de4923c40625299994f1b5ef750489913e92a824
